#!/usr/bin/env python

from setuptools import setup, find_packages

setup(
    name="plasmidextractor",
    version="0.1.2",
    packages=find_packages(),
    scripts=['plasmidextractor/Extractor.py', 'plasmidextractor/GeneSeekr.py'],
    author="Andrew Low",
    author_email="andrew.low@inspection.gc.ca",
    url="https://github.com/lowandrew/Plasmid_Assembler",
    install_requires=['biopython',
                      'OLCTools',
                      'alabaster',
                      'Babel',
                      'bz2file',
                      'certifi',
                      'chardet',
                      'CommonMark',
                      'cycler',
                      'Cython',
                      'docutils',
                      'idna',
                      'imagesize',
                      'Jinja2',
                      'khmer',
                      'MarkupSafe',
                      'matplotlib',
                      'numpy',
                      'Pygments',
                      'pyparsing',
                      'python-dateutil',
                      'pytz',
                      'PyYAML',
                      'recommonmark',
                      'requests',
                      'scipy',
                      'screed',
                      'six',
                      'snowballstemmer',
                      'sourmash',
                      'Sphinx',
                      'sphinxcontrib-websupport',
                      'urllib3']
)
